name: CI_FUZZ

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
defaults:
  run:
    working-directory: /
    
env:
  FUZZER_DAEMON_ADDRESS: grpc-api.cloud.code-intelligence.com:443
  PROJECT_NAME: simple-fuzzing
  COGNITO_USER: ${{secrets.COGNITO_USER}}
  COGNITO_PASSWORD: ${{secrets.COGNITO_PASSWORD}}
  REPORT_EMAIL: roque@code-intelligence.de

jobs:
  fuzz_fuzz_api_DoStuff:      
    runs-on: ubuntu-latest
    container: cifuzz/cictl
    
    steps:
    - name: Log-in with Cognito
      run: cictl login -u "${COGNITO_USER}" -p "${COGNITO_PASSWORD}"

    - name: Start fuzzing and wait for a crash for 5 minutes
      run: |
        cictl start_and_monitor_fuzzing \
        --daemon_listen_address="${FUZZER_DAEMON_ADDRESS}" \
        --project_name="${PROJECT_NAME}" \
        --campaign_name="fuzz_api_DoStuff" \
        --cloud_report_recipient_email="${REPORT_EMAIL}"
