name: CI

on:
#   push:
#     branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  PROJECT_NAME: simple-fuzzing  
  REPORT_EMAIL: roque@code-intelligence.com
  
jobs:
  fuzz_fuzz_api_DoStuff:      
    runs-on: ubuntu-latest
    steps:
      - id: start-fuzzing
        name: Build And Start Fuzzing
        uses: WillRoque/fuzzing-action/start-fuzzing@master
        with:
          cognito_user: ${{ secrets.COGNITO_USER }}
          cognito_password: ${{ secrets.COGNITO_PASSWORD }}
          project: ${{ env.PROJECT_NAME }}
          test_collection: "fuzz_api_DoStuff"          
          report_email: ${{ env.REPORT_EMAIL }}
          git_branch: ${GITHUB_REF#refs/*/}
#       - id: monitor-fuzzing
#         name: Monitor Fuzzing
#         uses: CodeIntelligenceTesting/github-actions/monitor-fuzzing@master
#         with:
#           cognito_user: ${{ secrets.COGNITO_USER }}
#           cognito_password: ${{ secrets.COGNITO_PASSWORD }}
#           project: ${{ env.PROJECT_NAME }}
#           test_collection_run: ${{ steps.start-fuzzing.outputs.test_collection_run }}
#       - id: report-coverage
#         name: Report Coverage
#         uses: CodeIntelligenceTesting/github-actions/report-coverage@master
#         if: ${{ success() || failure() }}
#         with:
#           cognito_user: ${{ secrets.COGNITO_USER }}
#           cognito_password: ${{ secrets.COGNITO_PASSWORD }}
#           project: ${{ env.PROJECT_NAME }}
#           test_collection: "fuzz_api_DoStuff"
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           pull_request_number: ${{ github.event.pull_request.number }}
#           owner: ${{ github.event.repository.owner.login }}
#           repository: ${{ github.event.repository.name }}
          
