# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "fuzz"
  fuzz:
    env:
      FUZZER_DAEMON_ADDRESS: grpc-api.cloud.code-intelligence.com:443
      PROJECT_NAME: simple-fuzzing
      CAMPAIGN_NAME: fuzz_api_DoStuff
      REPORT_EMAIL: roque@code-intelligence.de

    defaults:
      run:
        working-directory: /
      
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: cifuzz/cictl

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Log-in with Cognito
      run: ls && ./cictl login -u "${COGNITO_USER}" -p "${COGNITO_PASSWORD}"

    # Runs a set of commands using the runners shell
    - name: Start fuzzing and wait for a crash for 5 minutes
      run: |
        ./cictl start_and_monitor_fuzzing
        --daemon_listen_address="${FUZZER_DAEMON_ADDRESS}" \
        --project_name="${PROJECT_NAME}" \
        --campaign_name="${CAMPAIGN_NAME}" \
        --cloud_report_recipient_email="${REPORT_EMAIL}"
