name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  FUZZER_DAEMON_ADDRESS: grpc-api.cloud.code-intelligence.com:443
  PROJECT_NAME: simple-fuzzing  
  REPORT_EMAIL: roque@code-intelligence.de
  
jobs:
  fuzz_fuzz_api_DoStuff:      
    runs-on: ubuntu-latest
    steps:
      - id: start-fuzzing
        name: Start Fuzzing
        uses: CodeIntelligenceTesting/github-actions/start-fuzzing@master
        with:
          cognito-user: ${{ secrets.COGNITO_USER }}
          cognito-password: ${{ secrets.COGNITO_PASSWORD }}
          project: ${{ env.PROJECT_NAME }}
          test-collection: "fuzz_api_DoStuff"          
          report_email: ${{ env.REPORT_EMAIL }}
      - id: monitor-fuzzing
        name: Monitor Fuzzing
        uses: WillRoque/fuzzing-action/monitor-fuzzing@master
        with:
          cognito-user: ${{ secrets.COGNITO_USER }}
          cognito-password: ${{ secrets.COGNITO_PASSWORD }}
          project: ${{ env.PROJECT_NAME }}
          test-collection-run: ${{ steps.start-fuzzing.outputs.test-collection-run }}
          
